"""
labels.py
---------
Maps (attribution, confidence) to one of three transparency label variants.

The three variants are defined verbatim in planning.md §Transparency Label Design.
This module is the single source of truth for label text — app.py calls
generate_label() and never constructs label strings itself.

Thresholds (from planning.md):
  confidence <= 0.35  → likely_human  → Variant B
  0.36–0.64           → uncertain     → Variant C
  confidence >= 0.65  → likely_ai     → Variant A
"""


def generate_label(attribution: str, confidence: float) -> str:
    """
    Return the full transparency label text for a given attribution result.

    Args:
        attribution: "likely_ai" | "uncertain" | "likely_human"
        confidence:  float 0.0–1.0 (used to populate {confidence_pct})

    Returns:
        The full label string a user would see on the platform.

    Note: Variant C intentionally omits the confidence percentage because
    showing "48% AI" for an uncertain result would be misleading — it implies
    precision the system doesn't have at the boundary.
    """
    confidence_pct = round(confidence * 100)

    if attribution == "likely_ai":
        return (
            f"⚠️ AI-Generated Content Detected\n\n"
            f"Our analysis indicates this content was likely created with AI assistance "
            f"(confidence: {confidence_pct}%). This label is based on two independent "
            f"signals: a language model assessment and a statistical writing-style analysis.\n\n"
            f"If you are the creator and believe this is incorrect, you can submit an "
            f"appeal below. Appeals are reviewed by our moderation team."
        )

    elif attribution == "likely_human":
        return (
            f"✅ Human-Written Content\n\n"
            f"Our analysis suggests this content was written by a person, not generated "
            f"by AI (confidence: {confidence_pct}%). This label reflects automated "
            f"analysis and is not a guarantee.\n\n"
            f"If you believe this assessment is wrong, you can submit an appeal below."
        )

    else:  # "uncertain"
        return (
            f"🔍 Attribution Unclear\n\n"
            f"Our automated analysis could not confidently determine whether this content "
            f"was written by a person or generated by AI. This does not imply wrongdoing — "
            f"some writing styles are difficult to assess automatically.\n\n"
            f"If you are the creator, you may submit an appeal to add context that can "
            f"help our moderation team make a more informed review."
        )


def score_to_attribution(confidence: float) -> str:
    """
    Map a confidence score to an attribution string.

    Thresholds from planning.md §Uncertainty Representation.
    The uncertain band is intentionally wide (0.36–0.64) because a false
    positive — labeling a human's work as AI — is worse than a false negative
    on a creative writing platform.

    Args:
        confidence: float 0.0–1.0

    Returns:
        "likely_ai" | "uncertain" | "likely_human"
    """
    if confidence >= 0.65:
        return "likely_ai"
    elif confidence <= 0.35:
        return "likely_human"
    else:
        return "uncertain"