"""
signals.py
----------
Detection signal functions for Provenance Guard.

Milestone 3: Signal 1 — LLM-based classifier via Groq.
Milestone 4: Signal 2 — Stylometric heuristics engine (added later).

Each signal function is intentionally standalone — it takes raw text and
returns a float 0.0–1.0. This makes them independently testable before
they're wired into the submission endpoint.

  0.0 = very likely human-written
  1.0 = very likely AI-generated
"""

import os
import json
import re
import math
from groq import Groq

# ---------------------------------------------------------------------------
# Signal 1: LLM-based classifier (Groq)
# ---------------------------------------------------------------------------

# The system prompt instructs the model to behave as a classifier, not an
# assistant. Key design decisions:
#   - "ONLY a JSON object" → prevents preamble/explanation bleeding into output
#   - Explicit 0.0–1.0 scale with anchors → consistent scoring
#   - Listed AI "tells" → guides the model toward the properties we care about
#     (uniform register, hedging phrases, comprehensive structure)
#   - "Do not add explanation" → keeps parsing deterministic
_LLM_SYSTEM_PROMPT = """You are an AI content detection classifier. Your sole task is to assess
whether a given piece of text was written by a human or generated by an AI language model.

Analyze the text for these properties that distinguish AI-generated writing:
- Unusually consistent formality or register throughout the piece
- Generic transitional phrases ("It is important to note", "Furthermore", "In conclusion")
- Perfectly balanced treatment of all sides of an issue
- Uniform sentence length with little variation
- Absence of personal voice, idiosyncratic word choices, or unexpected associations
- Topics covered comprehensively and symmetrically, as if from a checklist

Respond with ONLY a JSON object in this exact format, with no preamble, no explanation, and
no markdown formatting:

{"ai_probability": <float between 0.0 and 1.0>}

Where:
  0.0 = extremely confident this is human-written
  0.5 = genuinely uncertain
  1.0 = extremely confident this is AI-generated

Do not add any text outside the JSON object."""


def classify_with_llm(text: str) -> float:
    """
    Signal 1: Send text to Groq's llama-3.3-70b-versatile and get back a
    probability that the content is AI-generated.

    Args:
        text: The raw submitted text to classify.

    Returns:
        Float in [0.0, 1.0]. Higher = more likely AI-generated.

    Raises:
        ValueError: if the API response cannot be parsed as a valid probability.
        Exception:  passes through Groq API errors (connection, auth, etc.)
                    so the caller (app.py) can return a 500 to the client.

    How it works:
        1. Initialize the Groq client (reads GROQ_API_KEY from environment).
        2. Send the text as a user message with our classifier system prompt.
        3. Parse the response as JSON and extract "ai_probability".
        4. Clamp the value to [0.0, 1.0] as a safety measure.
    """
    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _LLM_SYSTEM_PROMPT},
            {"role": "user",   "content": text}
        ],
        # temperature=0 makes the model deterministic / consistent for the
        # same input — critical for a classifier that should be reproducible.
        temperature=0,
        max_tokens=50,   # The response should be < 30 chars; 50 is generous
    )

    raw = response.choices[0].message.content.strip()

    # Strip any accidental markdown fences the model might add despite instructions
    raw = raw.replace("```json", "").replace("```", "").strip()

    try:
        parsed = json.loads(raw)
        score = float(parsed["ai_probability"])
    except (json.JSONDecodeError, KeyError, TypeError, ValueError) as e:
        raise ValueError(
            f"LLM returned unparseable response: {repr(raw)}"
        ) from e

    # Clamp to [0.0, 1.0] — the model should always be in range, but be safe
    return max(0.0, min(1.0, score))


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics engine (added in Milestone 4)
# ---------------------------------------------------------------------------

# Normalization bounds — calibrated against sample texts.
# Higher raw metric value → more human-like → lower AI score.
# See planning.md "Detection Signals → Signal 2" for full rationale.
_SLV_MIN, _SLV_MAX = 0.15, 0.65   # coefficient of variation of sentence word-counts
_TTR_MIN, _TTR_MAX = 0.40, 0.85   # unique tokens / total tokens
_PD_MIN,  _PD_MAX  = 0.01, 0.08   # non-period punctuation / total characters


def _clamp(value: float, lo: float, hi: float) -> float:
    """Clamp value to [lo, hi]."""
    return max(lo, min(hi, value))


def _sentence_length_variance(text: str) -> float:
    """
    Compute the coefficient of variation (std / mean) of word counts per sentence.

    Sentence splitting: we split on '.', '!', '?', and '\n' — crude but
    sufficient for prose. Short "sentences" under 2 words are discarded to
    avoid noise from initials, ellipses, etc.

    Returns 0.0 if fewer than 3 valid sentences (not enough data).
    """
    # Split on sentence-ending punctuation
    raw_sentences = re.split(r'[.!?\n]+', text)
    word_counts = [
        len(s.split())
        for s in raw_sentences
        if len(s.split()) >= 2   # discard fragments
    ]

    if len(word_counts) < 3:
        # Not enough sentences for a meaningful variance — return mid-range
        return (_SLV_MIN + _SLV_MAX) / 2

    mean = sum(word_counts) / len(word_counts)
    if mean == 0:
        return 0.0

    variance = sum((x - mean) ** 2 for x in word_counts) / len(word_counts)
    std_dev = math.sqrt(variance)
    return std_dev / mean   # coefficient of variation


def _type_token_ratio(text: str) -> float:
    """
    Compute unique word types / total word tokens.

    Preprocessing: lowercase, strip punctuation from token boundaries.
    Short texts naturally have higher TTR, so this metric is most reliable
    on texts > 80 words.

    Returns 0.0 for empty text.
    """
    # Tokenize: lowercase, keep only alphabetic/apostrophe characters
    tokens = re.findall(r"[a-z']+", text.lower())
    if not tokens:
        return 0.0
    return len(set(tokens)) / len(tokens)


def _punctuation_density(text: str) -> float:
    """
    Compute count of non-period punctuation / total character count.

    'Non-period' means: , ; : ! ? ( ) [ ] { } — – - ' "
    We exclude periods because AI text uses periods normally; it's the
    *variety* of other punctuation that differs.

    Returns 0.0 for empty text.
    """
    if not text:
        return 0.0
    # Match commas, semicolons, colons, !, ?, parentheses, brackets,
    # em-dashes, en-dashes, hyphens used as dashes
    non_period_punct = re.findall(r'[,;:!?()\[\]{}\-–—\'"]', text)
    return len(non_period_punct) / len(text)


def compute_stylometric_score(text: str) -> float:
    """
    Signal 2: Compute a stylometric AI-probability score for the given text.

    Steps:
      1. Compute three raw metrics: sentence-length variance (slv),
         type-token ratio (ttr), punctuation density (pd).
      2. Normalize each to [0, 1] against calibrated bounds.
         The inversion is intentional: higher human-like metric → lower AI score.
      3. Combine with weights: slv=50%, ttr=30%, pd=20%.

    Args:
        text: The raw submitted text.

    Returns:
        Float in [0.0, 1.0]. Higher = more AI-like stylometric profile.
    """
    slv = _sentence_length_variance(text)
    ttr = _type_token_ratio(text)
    pd  = _punctuation_density(text)

    # Invert: higher raw value (more human) → lower normalized AI score
    slv_norm = _clamp((_SLV_MAX - slv) / (_SLV_MAX - _SLV_MIN), 0.0, 1.0)
    ttr_norm = _clamp((_TTR_MAX - ttr) / (_TTR_MAX - _TTR_MIN), 0.0, 1.0)
    pd_norm  = _clamp((_PD_MAX  - pd)  / (_PD_MAX  - _PD_MIN),  0.0, 1.0)

    # Weighted combination (from planning.md)
    stylo_score = 0.50 * slv_norm + 0.30 * ttr_norm + 0.20 * pd_norm

    return round(stylo_score, 4)


# ---------------------------------------------------------------------------
# Confidence scoring (combines both signals — added in Milestone 4)
# ---------------------------------------------------------------------------

def compute_confidence(llm_score: float, stylo_score: float) -> float:
    """
    Combine the two signal scores into a single confidence value.

    Formula (from planning.md):
        confidence = 0.60 * llm_score + 0.40 * stylo_score

    The 60/40 weighting reflects that the LLM signal is semantically richer
    and typically more accurate on well-formed prose. Stylometric features
    provide an independent structural check.

    Returns:
        Float in [0.0, 1.0], rounded to 4 decimal places.
    """
    confidence = 0.60 * llm_score + 0.40 * stylo_score
    return round(_clamp(confidence, 0.0, 1.0), 4)


# ---------------------------------------------------------------------------
# Quick standalone test — run `python signals.py` directly to verify
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    test_inputs = [
        (
            "clearly_ai",
            """Your evaluation report is one of the strongest parts of this submission — the honest acknowledgment that the fine-tuned model underperformed the baseline, combined with detailed failure analysis, shows real intellectual maturity. Too many students would try to hide that result, but you leaned into it and extracted genuine insight about why the model confused reactions containing statistics with analysis posts. That kind of diagnostic thinking is exactly what makes someone effective at debugging ML systems in practice.\n\nThe most important area for growth is bridging the gap between your planning document and your actual implementation. Your planning.md has excellent edge case rules and decision criteria, but the Hard Annotation Decisions section Section 8 was left as placeholder templates — never filled in during annotation despite the spec requiring at least 3 documented cases there. You documented these cases in the README instead, which means your planning document does not reflect the actual annotation process as it happened. In real engineering work, keeping your design documents updated as you encounter reality is a discipline that pays off enormously: it creates an audit trail that helps you and teammates understand why decisions were made, and it catches drift between what you planned and what you built. Get in the habit of updating planning documents in real time rather than reconstructing decisions after the fact.The second area to focus on is your dataset relationship to model performance. Your confidence scores on misclassified examples are clustered tightly around 0.35–0.37, which means the model is essentially uncertain on nearly every prediction it gets wrong — and even some it gets right. You correctly identified that 195 examples across three structurally similar classes was not enough, but the deeper lesson is about data quality feedback loops: when you notice during annotation that boundary cases are frequent which your edge case documentation suggests, that is a signal to either simplify the taxonomy or dramatically increase the training set size for those boundary regions. Building that intuition — recognizing when your data is insufficient before training — will save you significant time in future ML projects."""
        ),
        (
            "clearly_ai",
            """Artificial intelligence represents a transformative paradigm shift in modern society.
It is important to note that while the benefits of AI are numerous, it is equally
essential to consider the ethical implications. Furthermore, stakeholders across
various sectors must collaborate to ensure responsible deployment."""
        ),
        (
            "clearly_human",
            """ok so i finally tried that new ramen place downtown and honestly?
underwhelming. the broth was fine but they put WAY too much sodium in it and
i was thirsty for like three hours after. my friend got the spicy version and
said it was better. probably won't go back unless someone drags me there"""
        ),
        (
            "borderline_formal_human",
            """The relationship between monetary policy and asset price inflation has been
extensively studied in the literature. Central banks face a fundamental tension
between their mandate for price stability and the unintended consequences of
prolonged low interest rates on equity and real estate valuations."""
        ),
        (
            "borderline_edited_ai",
            """I've been thinking a lot about remote work lately. There are genuine tradeoffs —
flexibility and no commute on one side, isolation and blurred work-life boundaries
on the other. Studies show productivity varies widely by individual and role type."""
        ),
    ]

    print("\n=== Stylometric scores (no API needed) ===")
    for label, text in test_inputs:
        score = compute_stylometric_score(text)
        print(f"  {label:<28} stylo_score = {score:.4f}")

    print("\n=== LLM scores (requires GROQ_API_KEY in environment) ===")
    from dotenv import load_dotenv
    load_dotenv()
    for label, text in test_inputs:
        try:
            score = classify_with_llm(text)
            print(f"  {label:<28} llm_score   = {score:.4f}")
        except Exception as e:
            print(f"  {label:<28} ERROR: {e}")